### ISSUE TITLE
启动服务时servces.py出现如下问题

### ISSUE THREAD

**Issue by maozida880** [xming521/WorkAggregation#21]
C:\Users\用户名\.conda\envs\虚拟环境\lib\site-packages\pymysql\_auth.py:8: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography. The next release of cryptography will remove support for Python 3.6.
  from cryptography.hazmat.backends import default_backend
[20.0, 7000.0, 9000.0, 12500.0, 250000.0]
 * Serving Flask app "server" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
C:\Users\用户名\.conda\envs\虚拟环境\lib\site-packages\pymysql\_auth.py:8: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography. The next release of cryptography will remove support for Python 3.6.
  from cryptography.hazmat.backends import default_backend
[20.0, 7000.0, 9000.0, 12500.0, 250000.0]
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\用户名\.conda\envs\虚拟环境\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Users\用户名\.conda\envs\虚拟环境\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\用户名\.conda\envs\虚拟环境\lib\site-packages\werkzeug\serving.py", line 966, in inner
    fd=fd,
  File "C:\Users\用户名\.conda\envs\虚拟环境\lib\site-packages\werkzeug\serving.py", line 790, in make_server
    host, port, app, request_handler, passthrough_errors, ssl_context, fd=fd
  File "C:\Users\用户名\.conda\envs\虚拟环境\lib\site-packages\werkzeug\serving.py", line 693, in __init__
    super().__init__(server_address, handler)  # type: ignore
  File "C:\Users\用户名\.conda\envs\虚拟环境\lib\socketserver.py", line 456, in __init__
    self.server_bind()
  File "C:\Users\用户名\.conda\envs\虚拟环境\lib\http\server.py", line 138, in server_bind
    self.server_name = socket.getfqdn(host)
  File "C:\Users\用户名\.conda\envs\虚拟环境\lib\socket.py", line 673, in getfqdn
    hostname, aliases, ipaddrs = gethostbyaddr(name)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd5 in position 0: invalid continuation byte

**Comment by maozida880** [comment]
这个是Hostname出现了中文，改成英文就可以了
